# Generated by Django 4.1.6 on 2023-03-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
        ('core', '0003_alter_wallet_emergency_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='category_list',
            field=models.ManyToManyField(related_name='categories', to='panel.category'),
        ),
    ]
