# Generated by Django 4.1.6 on 2023-02-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_wallet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='emergency_balance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
