# Generated by Django 4.1.6 on 2023-03-12 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_wallet_category_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='emergency_percentage',
            field=models.DecimalField(decimal_places=3, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
