# Generated by Django 4.1.6 on 2023-02-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_wallet_share_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='emergency_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
