# Generated by Django 4.1.6 on 2023-02-13 08:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='pay_list',
            field=models.ManyToManyField(related_name='pay_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
