# Generated by Django 4.1.6 on 2023-02-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_request_pay_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request_type',
            field=models.CharField(blank=True, default='expense', max_length=50, null=True),
        ),
    ]
