# Generated by Django 4.1.6 on 2023-02-19 05:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request', '0003_request_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='view_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='views', to=settings.AUTH_USER_MODEL),
        ),
    ]
