# Generated by Django 4.1.6 on 2023-02-21 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_alter_request_view_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='view_list',
        ),
    ]
