# Generated by Django 4.1.6 on 2023-02-22 05:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request', '0006_remove_request_view_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='approved_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='approves', to=settings.AUTH_USER_MODEL),
        ),
    ]
